### ISSUE TITLE
Finalize Documentation Site

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-geosearch-docs#13]
Let's discuss what should appear on the [docs page](https://geosearch.planninglabs.nyc/docs/). 

Currently is has content lifted randomly from Mapzen/Pelias docs (with some light editing). 

We should not port over the whole of Pelias docs. We _could_ link to them tho. Instead, the GeoSearch docs should cover the basics of the `search/` and `autocomplete/` endpoints, and custom features we've added. 

This issue is closed when we have written an outline of content to add to the docs and separate issues are made for each piece of content.

**Comment by chriswhong** [comment]
Let's state somewhere prominent that we are focused only on `autocomplete` and `search` endopoints of the pelias API, and link out to pelias for more information.

Clone docs for these two endpointsm remove anything we think is not necessary or relevant, and add context for NYC / Geosearch where necessary.
