### ISSUE TITLE
0 1/2 5 Avenue Manhattan

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-geosearch-docs#14]
0 1/2 5 Avenue Manhattan is the valid GeoSupport address, but users won't freeform search for the 0 prepended.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #29](https://github.com/NYCPlanning/labs-geosearch-docker/issues/29) via [**ZenHub**](https://www.zenhub.com/)
