### ISSUE TITLE
Issues with text input UI

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-geosearch-docs#17]
From internal testing using the docs site here in ITD:

I think it's safe to assume most of these were on IE11/Windows 7.

The first one can be addressed with debouncing, we should not send the API call until sufficient time has passed since the last keystroke.

> 
> There is a lag in the window accepting input. The issue is that during the lag, keystrokes are not being captured. A user will correct their input several times before they catch on that they need to type slowly.
>  
> After some input is entered, a user may need to make a correction or reach a new location by just changing a digit. For example, after entering 120 Broadway, a user may change the 20 in 120 to 55 in order to get to 155 Broadway. Instead of inserting the correction and pushing over the rest of the string, you end up overwriting the part of string that you want to remain. This happens intermittently.
>  
> After some input is entered , when deleting characters within the string, the curser will jump to the end of the string. If you are not careful, you inadvertently delete from the end of the string. This happens intermittently.
>  
> If you try to overwrite something, the curser will jump to the end of the string. This happens intermittently.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #27](https://github.com/NYCPlanning/labs-geosearch-docker/issues/27) via [**ZenHub**](https://www.zenhub.com/)
