### ISSUE TITLE
Multiple Locations Returned for Very Specific Search

### ISSUE THREAD

**Issue by mtreg** [NYCPlanning/labs-geosearch-docs#18]
Not sure which geosearch repo to flag this in, so hoping this is a reasonable spot... 

In using the API to search a very specific address (with city, state, borough, & zip code), but where the building number/street name occur in multiple boroughs, I was surprised to see GeoSearch returned occurrences of the building number/street NYC.

For example, as a sample here is the address of the Staten Island Zoo: 614 Broadway, Staten Island, NY 10310

[The API call of this](https://geosearch.planninglabs.nyc/v1/search?text=614%20Broadway,%20Staten%20Island,%20NY%2010310) seems to parse all fields correctly. However, results returned include 614 Broadway locations in Manhattan and Brooklyn as well as in Staten Island. 

([Searching for the specific address for the Staten Island Zoo returned by the api](https://geosearch.planninglabs.nyc/v1/search?text=614%20BROADWAY,%20Staten%20Island,%20New%20York,%20NY,%20USA) yields the same result.

I wasn't sure if this was expected behavior, but it surprised me given the specificity of the search, so figured I would flag. 

Hope this helps! 

(PS - in case it's useful to know, I'm not using this for development/production, more just exploring the functionality)

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #26](https://github.com/NYCPlanning/labs-geosearch-docker/issues/26) via [**ZenHub**](https://www.zenhub.com/)
