### ISSUE TITLE
Using the /search endpoint with borough information now results in a 500

### ISSUE THREAD

**Issue by toolness** [NYCPlanning/labs-geosearch-docs#21]
Hi!  For the [JustFix.nyc app](https://app.justfix.nyc) ([github repo](https://github.com/JustfixNYC/tenants2)) we use the `/search` endpoint of the GeoSearch API to geocode addresses.  All our queries are in the form `{{ STREET ADDRESS }}, {{ BOROUGH }}`, e.g. `654 PARK PLACE, BROOKLYN`.  Since the app's launch in fall of last year, this has worked fine, but ~~this week~~ starting February 14 we've started receiving an HTTP 500 response when making these kinds of requests.

That is, the following request:

https://geosearch.planninglabs.nyc/v1/search?text=654%20park%20place%2C%20brooklyn

now produces an HTTP 500 with the following JSON output:

```json
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://geosearch.planninglabs.nyc/attribution",
    "query": {
      "text": "654 park place, brooklyn",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "number": "654",
        "street": "park place",
        "borough": "brooklyn"
      }
    },
    "errors": [
      "getaddrinfo EAI_AGAIN placeholder placeholder:4100"
    ],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1550697162923
  },
  "type": "FeatureCollection",
  "features": []
}
```

The `getaddrinfo EAI_AGAIN` portion seems to indicate that this might be a networking issue on the NYC Planning Labs end but I'm not sure.  Also worth noting is that removing the Borough information from our search (that is, searching for only `654 park place`) results in a 200--but this is sub-optimal since it means that we might be passing-in an ambiguous address.

Sorry if this isn't the right place to file this issue, by the way!

**Comment by hannahkates** [comment]
Hi @toolness, thanks for flagging this. We just pushed out a fix to resolve it. Please let us know if it's still not working for you.

**Comment by toolness** [comment]
Oh wow, thanks for the super quick turnaround!
