### ISSUE TITLE
Test PAD 19c data in Geosearch

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/labs-geosearch-docs#24]
[https://app.zenhub.com/files/116979519/29aa00af-705f-4b74-ae0e-ab79369655da/download](https://app.zenhub.com/files/116979519/29aa00af-705f-4b74-ae0e-ab79369655da/download)

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-geosearch-docker #25](https://github.com/NYCPlanning/labs-geosearch-docker/issues/25) via [**ZenHub**](https://www.zenhub.com/)
