### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-geosearch-docs#6]

**Comment by andycochran** [comment]
IE also has a double X. Need to hide the default one and only show the custom one. 
![image](https://user-images.githubusercontent.com/409279/35239772-69b0e722-ff7f-11e7-8db6-82835704bc80.png)

**Comment by allthesignals** [comment]
Confirmed `fetch is undefined` error in IE. See https://github.com/github/fetch

**Comment by andycochran** [comment]
Fixed. 

<img src="http://www.sunlessinseattle.com/wp-content/uploads/2014/05/thatssofetch-e1401405763334.jpg" />
